import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <main>
                    <ChakraProvider>
                        {children}
                    </ChakraProvider>
                </main>
            </body>
        </html>
    );
}
